In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')

### Affine Function

In [2]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) # import setting ( input - > matrix )
print(x)

dence   = Dense(units = 1) # imp . an affine function

y_tf = dence(x) #forward propagation + parass initialization
print(y_tf)

W, B = dence.get_weights()
print(W, B)

y_man = tf.linalg.matmul(x,W)+B

print('========Input/Weight/Bias=========')
print("x : {}\n{}\n".format(x.shape,x.numpy()))
print("W : {}\n{}\n".format(x.shape,W))
print("B : {}\n{}\n".format(x.shape,B))
print('========output/Weight/Bias=========')
print("y(Tensorflow):{}\n{}\n)".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.72271705]], shape=(1, 1), dtype=float32)
[[0.0722717]] [0.]
========Input/Weight/Bias=========
x : (1, 1)
[[10.]]

W : (1, 1)
[[0.0722717]]

B : (1, 1)
[0.]

========output/Weight/Bias=========
y(Tensorflow):(1, 1)
[[0.72271705]]
)
y(Manual): (1, 1)
[[0.72271705]]



### Params Initalization

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]]) #input setting(Note : input ->matrix)

W,b = tf.constant(10.) , tf.constant(20.)

w_init,b_init = Constant(W), Constant(b)

dense = Dense(units = 1,
              activation = 'linear',
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)
print(y_tf)

W,B = dense.get_weights()

print("W :{}\n{}\n".format(W.shape,W))

print("W :{}\n{}\n".format(B.shape,B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W :(1, 1)
[[10.]]

W :(1,)
[20.]



### AFfine Function with n Features

In [4]:
x = tf.random.uniform(shape=(1,10),minval = 0, maxval = 10)

dense =Dense(units =1)

y_tf = dense(x)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W)+B

print('========Input/Weight/Bias=========')
print("x : {}\n{}\n".format(x.shape,x.numpy()))
print("W : {}\n{}\n".format(x.shape,W))
print("B : {}\n{}\n".format(x.shape,B))
print('========output/Weight/Bias=========')
print("y(Tensorflow):{}\n{}\n)".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))

========Input/Weight/Bias=========
x : (1, 10)
[[4.771324   2.2534072  0.77728987 2.1276617  6.65591    5.08669
  1.0631883  5.1347103  8.085903   7.146879  ]]

W : (1, 10)
[[ 0.49652284]
 [-0.4737992 ]
 [ 0.73605734]
 [-0.6379984 ]
 [-0.6505192 ]
 [ 0.58252674]
 [-0.35034952]
 [ 0.71803623]
 [-0.64242077]
 [-0.46106607]]

B : (1, 10)
[0.]

========output/Weight/Bias=========
y(Tensorflow):(1, 1)
[[-6.0258856]]
)
y(Manual): (1, 1)
[[-6.0258856]]



## Activation Function

### Activation Layer

In [7]:
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape = (1,5))

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

y_sigmoid_man = 1 / (1+exp(-x))
y_tanh_man = (exp(x) - exp(-x)/exp(x) +exp(-x))
y_relu_man = maximum(x, 0)

print("x = {}\n{}".format(x.shape,x.numpy()))
print("sigmoid(Tensorflow) :{}\n{}".format(y_sigmoid_tf.shape,y_sigmoid_tf.numpy()))
print("sigmoid(manual) :{}\n{}".format(y_sigmoid_man.shape,y_sigmoid_man.numpy()))
print()


print("Tanh(Tensorflow) :{}\n{}".format(y_tanh_tf.shape,y_tanh_tf.numpy()))
print("Tanh(manual) :{}\n{}".format(y_tanh_man.shape,y_tanh_man.numpy()))
print()

print("ReLU(Tensorflow) :{}\n{}".format(y_relu_tf.shape,y_relu_tf.numpy()))
print("ReLU(manual) :{}\n{}".format(y_relu_man.shape,y_relu_man.numpy()))

x = (1, 5)
[[-0.49831426  1.607688    0.13153286  1.0814048  -2.523739  ]]
sigmoid(Tensorflow) :(1, 5)
[[0.37793693 0.8330901  0.5328359  0.7467598  0.07421066]]
sigmoid(manual) :(1, 5)
[[0.37793693 0.8330901  0.5328359  0.7467598  0.07421066]]

Tanh(Tensorflow) :(1, 5)
[[-0.46079043  0.92281765  0.1307795   0.7937195  -0.987231  ]]
Tanh(manual) :(1, 5)
[[  -0.45563447    5.151468      1.2486343     3.172936   -143.07417   ]]

ReLU(Tensorflow) :(1, 5)
[[0.         1.607688   0.13153286 1.0814048  0.        ]]
ReLU(manual) :(1, 5)
[[0.         1.607688   0.13153286 1.0814048  0.        ]]


### Activation in Dense Layer

In [12]:
dense_sigmoid = Dense(units = 1 , activation = 'sigmoid')
dense_tanh = Dense(units = 1 , activation = 'tanh')
dense_relu = Dense(units = 1 , activation = 'relu')

y_sigmoid_tf = dense_sigmoid(x)
y_tanh_tf = dense_tanh(x)
y_relu_tf = dense_relu(x)


print("An with Sigmoid= {}\n{}".format(y_sigmoid_tf.shape,y_sigmoid_tf.numpy()))
print("An with  Tanh :{}\n{}".format(y_tanh_tf.shape,y_tanh_tf.numpy()))
print("An with  RelU:{}\n{}".format(y_relu_tf.shape,y_relu_tf.numpy()))

print('\n=========\n')

W,B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W) +B
a = 1/(1+exp(-z))

print("Activation value(Tensorflow)= {}\n{}".format(y_sigmoid_tf.shape,y_sigmoid_tf.numpy()))
print("Activation value(manual)= {}\n{}".format(a.shape, a.numpy()))

An with Sigmoid= (1, 1)
[[0.5140446]]
An with  Tanh :(1, 1)
[[0.05613386]]
An with  RelU:(1, 1)
[[0.05619291]]


Activation value(Tensorflow)= (1, 1)
[[0.5140446]]
Activation value(manual)= (1, 1)
[[0.5140446]]


### Artificial Nuerons

In [15]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activation = 'sigmoid'
# activation = 'tanh'
activation = 'relu'

x = tf.random.uniform(shape = (1,10))

dense = Dense(units =1, activation = activation)

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually 
y_man = tf.linalg.matmul(x,W) +B

if activation == 'sigmoid':
    y_man = 1/(1 + exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man))/(exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(y_man, 0)

print("Activation : ",activation)
print("Y_tf : {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("Y_man : {}\n{}\n".format(y_man.shape, y_man.numpy())) 

Activation :  relu
Y_tf : (1, 1)
[[0.]]

Y_man : (1, 1)
[[0.]]



## Minibatches

### Shapes of Dense Layers

In [21]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8 ,10
x = tf.random.normal(shape = (N , n_feature)) # generate minibatch

dense = Dense(units =1 ,  activation = 'relu') 

y = dense(x) # foward propagation 

W,B = dense.get_weights()

print("shape of x : {}",x.shape)
print("shape of W : {}",W.shape)
print("shape of B : {}",B.shape)


shape of x : {} (8, 10)
shape of W : {} (10, 1)
shape of B : {} (1,)


In [24]:
N, n_feature = 8, 10
x = tf.random.normal(shape = (N ,n_feature))

dense = Dense(units =1, activation = 'sigmoid' )
y_tf  = dense(x)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) +B
y_man = 1/ (1 +tf.math.exp(-y_man))

print("Output(Tensorflow) : \n",y_tf.numpy())
print()
print("Output(Manual) : \n",y_man.numpy())

Output(Tensorflow) : 
 [[0.05373602]
 [0.25341251]
 [0.18336044]
 [0.7859914 ]
 [0.04279922]
 [0.3482342 ]
 [0.81956345]
 [0.80775386]]

Output(Manual) : 
 [[0.05373602]
 [0.25341251]
 [0.18336044]
 [0.7859914 ]
 [0.04279922]
 [0.3482342 ]
 [0.81956345]
 [0.80775386]]
